/*
 * nls.h - Definitions for Native Language Support
 *
 * For use with compiled-in resources,
 * generated by nlsdump
 *
 * Authors:
 *  LVL   Laurent Vogel
 *
 * This file is distributed under the GPL, version 2 or at your
 * option any later version.  See doc/license.txt for details.
 */

#ifndef NLS_H
#define NLS_H

#include "country.h"

typedef unsigned short nls_key_offset;

/*
 * Possible plural forms supported
 */
enum {
	PLURAL_NONE,        /* nplurals=1; plural=0; */
	PLURAL_NOT_ONE,     /* nplurals=2; plural=n != 1; (most common) */
	PLURAL_GREATER_ONE, /* nplurals=2; plural=(n > 1); (eg. fr, pt_BR *) */
	PLURAL_CS,          /* nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2; (also used for sk) */
	PLURAL_HR,          /* nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2); (also used for sr) */
	PLURAL_LV,          /* nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2); */
	PLURAL_PL,          /* nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2); */
	PLURAL_RO,          /* nplurals=3; plural=n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < 20)) ? 1 : 2; */
	PLURAL_RU,          /* nplurals=4; plural=n==1 ? 3 : n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2; */
	PLURAL_LT,          /* nplurals=4; plural=(n==1 ? 0 : n%10>=2 && (n%100<10 || n%100>=20) ? 1 : n%10==0 || (n%100>10 && n%100<20) ? 2 : 3); */
	PLURAL_SL,          /* nplurals=4; plural=(n%100==1 ? 1 : n%100==2 ? 2 : n%100==3 || n%100==4 ? 3 : 0); */
	PLURAL_GA,          /* nplurals=5; plural=n==1 ? 0 : n==2 ? 1 : n<7 ? 2 : n < 11 ? 3 : 4 */
};

#define ISO639_CODE_LEN 5

typedef struct _nls_domain {
	language_t tos_country_code;
	char lang_id[ISO639_CODE_LEN + 1];
	int plural_form;
	const char *translations;
	const nls_key_offset *const *hash;
} nls_domain;

const char *nls_dgettext(const nls_domain *domain, const char *key) __attribute__((__format_arg__(2)));

/* initialisation */

char *nls_setlocale(int category, const char *locale);

void nls_init(nls_domain *domain);

extern nls_domain nls_current_domain;
extern const nls_domain *const nls_languages[];

/* not needed with compiled-in sources */
#define textdomain(domain)
#define bindtextdomain(domain, directory)
#define bind_textdomain_codeset(domain, codeset)

/* the gettext-like macros */
#ifdef ENABLE_NLS
# define N_(a) a
# define _(a) nls_gettext(a)
# define nls_gettext(key) nls_dgettext(&nls_current_domain, key)
# define setlocale(category, locale) nls_setlocale(category, locale)
#else
# define N_(a) a
# define _(a) a
#endif

#endif /* NLS_H */
